name: Build Package

on:
  workflow_call:

env:
  APP_NAME: lumio

jobs:
  build_windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@5bef47975285e477b672ce87764f851fbb5fd6ab # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 Nodejs
        uses: puniyu/setup-node@616da89a9057e53cc699ad95bcd3250d68c4d5bf # main
        with:
          node-version: lts/*
          pnpm-version: latest

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: lumio_node

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            lumio_node/dist/${{ env.APP_NAME }}*.node

  build_macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@5bef47975285e477b672ce87764f851fbb5fd6ab # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 Nodejs
        uses: puniyu/setup-node@616da89a9057e53cc699ad95bcd3250d68c4d5bf # main
        with:
          node-version: lts/*
          pnpm-version: latest

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: lumio_node

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            lumio_node/dist/${{ env.APP_NAME }}*.node

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
            container: ghcr.io/pragmatrix/rust-skia-linux:latest
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64
            container: ghcr.io/pragmatrix/rust-skia-linux-arm64:latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 设置 rust
        uses: puniyu/setup-rust@5bef47975285e477b672ce87764f851fbb5fd6ab # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 Nodejs
        uses: puniyu/setup-node@616da89a9057e53cc699ad95bcd3250d68c4d5bf # main
        with:
          node-version: lts/*
          pnpm-version: latest

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: lumio_node

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            lumio_node/dist/${{ env.APP_NAME }}*.node


      - name: 上传npm包
        if: matrix.platform.label == 'linux-x86_64'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "npm-package"
          path: |
            lumio_node/dist/index.js
            lumio_node/dist/index.d.ts
            lumio_node/package.json