name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.release-please.outputs['lumio_core--release_created'] }}
      help: ${{ steps.release-please.outputs['lumio_help--release_created'] }}
      lumio: ${{ steps.release-please.outputs['lumio--release_created'] }}
      node: ${{ steps.release-please.outputs['lumio_node--release_created'] }}
      node_tag_name: ${{ steps.release-please.outputs['lumio_node--tag_name'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json


  publish-lib:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: needs.release.outputs.core == 'true' || needs.release.outputs.help == 'true' || needs.release.outputs.lumio == 'true'
    steps:
      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 Rust 工具链
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - name: 设置 Rust 缓存
        uses: swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: 发布 lumio_core
        if: needs.release.outputs.core == 'true'
        run: cargo publish --package lumio_core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布 lumio_help
        if: needs.release.outputs.help == 'true'
        run: cargo publish --package lumio_help
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布 lumio
        if: needs.release.outputs.lumio == 'true'
        run: cargo publish --package lumio
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}


  build:
    needs: release
    if: needs.release.outputs.node == 'true'
    uses: ./.github/workflows/build.yml

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ release, build ]
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载 npm 包
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: npm-package
          path: lumio_node

      - name: 下载构建产物
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: lumio-node*
          path: lumio_node/artifacts

      - name: 配置 Nodejs
        uses: puniyu/setup-node@616da89a9057e53cc699ad95bcd3250d68c4d5bf # main
        with:
          node-version: lts/*
          pnpm-version: latest

      - name: 发布 npm 包
        run: |
          pnpm i -g @napi-rs/cli
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: lumio_node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 上传 Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            lumio_node/artifacts/lumio-node-*/*.node
          tag_name: ${{ needs.release.outputs.node_tag_name }}

